### PR TITLE
[MENFORCER-353] Formatting of artifact same as dependency:tree

### PR DESCRIPTION
**Pull request by royvanrijn**
Instead of combining fields of an artifact by appending fields I've changed this to use artifact.toString() just as the dependency:tree plugin is doing.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MENFORCER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MENFORCER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MENFORCER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by michael-o** [comment]
Can you show a before and after?

**Comment by royvanrijn** [comment]
Absolutely, I've followed the sample from:
https://issues.apache.org/jira/browse/MENFORCER-353

This is the before:

```[WARNING] 
Dependency convergence error for com.google.inject:guice:4.1.0 paths to dependency are:
+-test.example.com:test:1.0.0-SNAPSHOT
  +-org.testng:testng:7.1.0
    +-com.google.inject:guice:4.1.0
and
+-test.example.com:test:1.0.0-SNAPSHOT
  +-org.apache.maven:maven-core:3.5.0
    +-com.google.inject:guice:4.0
```

 And this is the after:
```[WARNING] 
Dependency convergence error for com.google.inject:guice:jar:no_aop:4.1.0:compile paths to dependency are:
+-com.mycompany.app:my-app:jar:1
  +-org.testng:testng:jar:7.1.0:compile
    +-com.google.inject:guice:jar:no_aop:4.1.0:compile
and
+-com.mycompany.app:my-app:jar:1
  +-org.apache.maven:maven-core:jar:3.5.0:compile
    +-com.google.inject:guice:jar:no_aop:4.0:compile
```

Formatting is now the same as dependency:tree (as requested).

**Comment by michael-o** [comment]
https://builds.apache.org/job/maven-box/job/maven-enforcer/job/MENFORCER-353/1/

**Comment by jira-importer** [comment]
Resolve #469

**Pull request closed without merging**
