### PR TITLE
remove specific IDE m2e files

### PR DESCRIPTION
**Pull request by olamy**
those files are specific to m2e they shouldn;t be stored in the Apache Maven sources!

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MENFORCER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MENFORCER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MENFORCER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by olamy** [comment]
cc @HannesWell @kwin

**Review by HannesWell — APPROVED** [review]
This should be safe as well, since this is also handled by M2E's default lifecycle-mappings.

https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.core/lifecycle-mapping-metadata.xml#L51-L65

**Review by khmarbaise — APPROVED** [review]

**Review by slawekjaranowski — APPROVED** [review]

**Comment by vtintillier** [comment]
Hello @olamy 

I think this is a regression for all users of Eclipse and maven-enforcer-plugin. We now have a warning in all our pom files because of this change:

image

It means this change forces all those projects to each find a way to ignore this warning. And for now I have not found a way to do it on my side.

The goal of this `META-INF/m2e/lifecycle-mapping-metadata.xml` file is just to declare whether it makes sense to run this plugin in Eclipse or not, so that not all projects have to declare it on their side.

Would you consider reverting this change to help all those projects? Especially given there was no maintenance on this file for 8 years in this project, so not really costing this project anything.

Thanks a lot

**Comment by kwin** [comment]
@vtintillier Please raise an issue with m2e (at  https://github.com/eclipse-m2e/m2e-core/issues) as the action `ignore` in https://github.com/eclipse-m2e/m2e-core/blob/e3794059b1250729872daecf9c1ff0b35fc75daf/org.eclipse.m2e.core/lifecycle-mapping-metadata.xml#L130 is the culprit.

**Comment by vtintillier** [comment]
Hi @kwin 

looks like the ignore in the file you linked to has a different behavior than what we had with the `META-INF/m2e/lifecycle-mapping-metadata.xml` hosted in maven-enforcer-plugin itself. Before this file was removed, there would be no warning at all in Eclipse, and enforcer would not run as part of the Eclipse build.

Now enforcer still don't run, but we have this warning.

I asked about this in m2e too: https://github.com/eclipse-m2e/m2e-core/discussions/1229
But I think the easiest way forward is to add this file again.

Thanks

**Comment by olamy** [comment]
Sorry for the disagreement but this file should have never been added.. 
But your problem should be solved by m2e plugin.
Imagine if every single IDE asks to host their configuration file.

**Pull request merged**
