### PR TITLE
[MENFORCER-336] - Fixes race condition in EvaluateBeanshell

### PR DESCRIPTION
**Pull request by vbreivik**
The Beanshell interpreter in EvaluateBeanShell was a static field, but this object is not thread safe. I wrapped the BeanShell interpreter in a ThreadLocal. The alternative would be to create a new Interpreter on each invocation, but I don't know how expensive the Interpreter object is. Using ThreadLocal is probably closer to the original design where it was a singleton. 

I added a (somewhat naive) unit test that failed on every run on my old 4 core mac, and ran green with the new ThreadLocal variant. However I am not sure if this is the correct way to test this, or how this will behave on other hardware. 

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MENFORCER-336) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MENFORCER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MENFORCER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by vbreivik** [comment]
> Thanks. I think this change might require signing an Apache Individual Contributor License Agreement.

Ah, sorry about that. I won't have access to a printer and scanner for some weeks, but I will sign and send it when I get a chance.

**Comment by olamy** [comment]
the change is not that big. we don't need a CLA. by contributing you agree to the license it's implicit and by the way you do not add any new files but simply modify files under Apache license.

**Comment by vbreivik** [comment]
> the change is not that big. we don't need a CLA. by contributing you agree to the license it's implicit and by the way you do not add any new files but simply modify files under Apache license.

I will leave it up to you to decide. I do have another pull request open for another plugin, so I will sign the CLA when I get access to a scanner again.

**Comment by jira-importer** [comment]
Resolve #812

**Pull request merged**
