### PR TITLE
[MENFORCER-394] Only look at shipped dependencies in DependencyConvergence

### PR DESCRIPTION
**Pull request by josephlbarnett**
This matches the 3.0.0-M3 behavior of the DependencyConvergence rule,
including only non-optional compile and runtime dependencies.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by rfscholte** [comment]
This deserves an integration test

**Comment by josephlbarnett** [comment]
Looks like there was an integration test for this case designed to fail, so I've set it to pass instead.  not sure how that test was successful in 3.0.0-M3 though?

**Comment by kgunnerud** [comment]
Great that this will be fixed. After upgrading to Spring Boot 2.5.4 which was released yesterday, they bumped maven-enforcer-plugin version and a lot of convergence was reported on dependencies that had provided scope. In a self-contained fat-jar few provided resources actually will be provided.

**Comment by josephlbarnett** [comment]
@rfscholte any feedback on next steps here?

**Comment by rfscholte** [comment]
I need to push some plugins in preparation of Java 17 first. Also want to understand the change to `dependencies_not_converging_test_scope/invoker.properties `.

**Review by slachiewicz — APPROVED** [review]

**Comment by slachiewicz** [comment]
merged, thx

**Comment by vebits** [comment]
Any ETA on a 3.0.1 release with this change? @slachiewicz

**Comment by Stephan202** [comment]
@slachiewicz this issue has prevented us from upgrading `maven-enforcer-plugin` for over half a year now. Any chance of a new release in the near future? :pray:

**Comment by slawekjaranowski** [comment]
@Stephan202 , @vebits please drop a line on Maven dev list ...

**Pull request closed without merging**
