### PR TITLE
[MENFORCER-332] Dependency graph performance fix

### PR DESCRIPTION
**Pull request by rjatkins**
Fixes main performance issue in bannedDependencies, and other rules that use DependencyGraphBuilder or the legacy DependencyTreeBuilder.

 - [/] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by rjatkins** [comment]
The upgrade of maven-dependency-tree has changed the semantics of what it means to build a dependency graph, since it removed the DependencyTreeBuilder and replaced it with DependencyGraphBuilder, which has broken the integration tests for DependencyConvergence and RequireUpperBoundDeps. I'm digging into what needs to be done to make the graph compatible with both of these, which requires debugging through mrm-maven-plugin to find out why it's not serving all the required mock poms and jars. I hope to have a fix for this tomorrow.

**Comment by rjatkins** [comment]
The remaining test failures in RequireUpperBoundDeps needs a fix in mrm-maven-plugin to add support for mocking timestamped snapshots (fixed in https://github.com/mojohaus/mrm/pull/22 ), and another fix in maven-dependency-tree to restore support for annotating DependencyNodes with managed versions and scopes (tracked in https://issues.apache.org/jira/browse/MSHARED-816 with a fix in https://github.com/apache/maven-dependency-tree/pull/2 ).

**Comment by elharo** [comment]
Since this is over a year old, I'm going to close it. Feel free to open a new PR that resolved the merge conflicts.

**Comment by jira-importer** [comment]
Resolve #813

**Pull request closed without merging**
