### PR TITLE
[MENFORCER-331] - Maven-enforcer-rules to use maven-resolver-util.

### PR DESCRIPTION
**Pull request by suztomo**
# Why
As of now maven-enforcer-rule has a transitive dependency on `org.eclipse.aether:aether-util` (released 2013) that contains  `org.eclipse.aether.util.ConfigUtils` (via maven-dependency-tree)

This old artifact causes a dependency conflict (`NoSuchMethodError` on `org.eclipse.aether.util.ConfigUtils.getFloat`) in maven-resolver-util (released 2019) when maven-enforcer-rules and maven-resolver-util are used together. 

# How
This pull request excludes `org.eclipse.aether:aether-util` (released 2013) from `org.apache.maven.shared:maven-dependency-tree` and adds dependency to `org.apache.maven.resolver:maven-resolver-util` (released 2019).

Originally I thought upgrading `org.apache.maven.shared:maven-dependency-tree` to use maven-resolver-util. However, `org.apache.maven.shared:maven-dependency-tree` cannot depend on libraries compiled with Java 7. So I'm trying to fix this at maven-enforcer-rules.

----------------------------

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MENFORCER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MENFORCER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MENFORCER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

Yes, the change is under ~20 lines.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by suztomo** [comment]
Thank you.

**Comment by suztomo** [comment]
@eolivelli Would you merge this? (Not sure who has write access to merge this PR)

**Comment by suztomo** [comment]
@rfscholte Hi Robert,
(I found you have write access, as per your last commit) Is it possible for you to merge this pull request? This has been approved by @eolivelli .

**Comment by eolivelli** [comment]
@suztomo link to CI
https://builds.apache.org/job/maven-box/job/maven-enforcer/job/MENFORCER-311/
We can merge it to master as soon as it finished without errors.

I apologize this took so much time !

**Comment by eolivelli** [comment]
merged as 9c0ea9c70e139e778698a4f7f66cceae3ea19e5a

**Comment by jira-importer** [comment]
Resolve #811

**Pull request closed without merging**
