### PR TITLE
[MENFORCER-324] - Shouldn't we use System.lineSeparator() instead?

### PR DESCRIPTION
**Pull request by jsoref**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MENFORCER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MENFORCER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MENFORCER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.

This tries to address a request by @khmarbaise in https://github.com/apache/maven-enforcer/pull/47#discussion_r240368459

 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by eolivelli** [comment]
@jsoref thank you for sending this patch.

Before merging this PR I have to understand @khmarbaise  and @Tibor17 concerns.
Does any Windows user ever reported problems with new lines ? I guess that Java or some other layer translates '\n' to the correct EOL depending on the platform.

**Comment by jsoref** [comment]
@eolivelli: I'm not endorsing this PR. I provided it based on their requests. I'm using macOS and this isn't a concern I have.

If you're curious about the behavior, you can use

Microsoft [Win 7/Win 8.1/Win 10](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) in [VirtualBox](https://www.virtualbox.org/wiki/Downloads) for free and install Java/maven/maven-enforcer.

**Comment by Tibor17** [comment]
@eolivelli 
If the user does not want to continue, we can take over.
Java is quite redundant language and we can make better if we put a public static final constant `NL` in `EnforcerUtils` and replace all these calls. These changes remind me to say that there are these code constructs:
`stingBuilder.append( "a" + "b" )` which should be transformed to two calls of `append`.
 If we do it, we should do it properly.
On the other side the reason for these strings is displaying a message on console and the messages are never so big that we have to use `StringBuilder` as performance optimizer. Humans are not able to react on changes below 0.3 seconds and these CPUs can concatenate Kilo bytes of strings within microseconds.
There I use to make a compromises in my codes because `javac 1.5+` translates simple concatenation `"a" + "b"` to the same code with `StringBuilder` in bytecode except the loops. Making more compact Java code with a slowness cca 1 microsecond is still perfect for creating these Exception messages. And anyway if we construct Exception it means that the build is going to fail and there such delay 1E-6 seconds does not matter at all even if it was 1E-3 seconds.

**Comment by eolivelli** [comment]
I think that we don't need this change if noone ever reported errors on Windows and Mac.

I appreciate @jsoref work and the fact that he is responding to suggestions and requests of the maintainers of this code base.

The initial request was Karl

**Comment by Tibor17** [comment]
@eolivelli 
Correct!
I think the main change in https://github.com/apache/maven-enforcer/pull/47 can be pushed even with `\n`. If somebody is shouting in users, we will fix new lies then.

**Comment by jsoref** [comment]
@eolivelli: rebased, but if you guys aren't particularly certain you want to take it, I really don't want to push this much past where it is now.

And yes, I'm aware of @Tibor17 's concerns w/ `StringBuilder`, I considered it and concluded for more or less the same reasons that @Tibor17 did that there wasn't any particular value in doing more than I did. -- I used a set of pure search and replaces (plus eventually fixing line widths), whereas proper StringBuilder would have required me to actually read all the code.

**Comment by michael-o** [comment]
@eolivelli @Tibor17 anything holding us off merging @jsoref's work? Looks good to me now.

**Comment by Tibor17** [comment]
No objections from me. Go ahead!

**Comment by eolivelli** [comment]
Seems to me and to the contributor himself that this change is not needed.
Are there any other cases in other plugins ?
We should keep consistent behavior among all the plugins.

I am -0 on this patch.
Feel free to commit but I think we can leave without it.

I appreciate the work and patience of @jsoref . Thank you

**Comment by michael-o** [comment]
@eolivelli why? Line ending consistency is important. There a hundreds of spots in our codebase which is inconsistent. I, therefore, appreciate this PR.

**Comment by eolivelli** [comment]
@michael-o does any user ever reported any problem with the output of this plugin ?

I think that somehow on Windows (on Linux I am sure it is already working well) there is something which is making the output nicer. Something that is already translating the new line to the corresponding platform dependant value.

I think that that constant is to be used when writing to a file for instance, not to stdout.

So if no one ever complained why changing the code ? We could introduce some regression hard to  debug.
What's your opinion ?

**Comment by michael-o** [comment]
No one needs to complain to make things better. I fixed a lot of stuff last year in Maven SCM where no one complained, but I have stumbled upon because they were just broken in that specific constellation. Having a consistent `stdout` which can be written to a file is a good thing.

**Comment by eolivelli** [comment]
@michael-o 
fine to me, let's merge this one.
Thank you for your clarification.

I feel it would be useful to raise this point to dev list and clean up other plugins. So that when a committer works on a plugin he has a change to clean up line endings writes to stdout

**Comment by michael-o** [comment]
@eolivelli I have done that actually in places I have found. Feel free to work on that kind of stuff and request a review by some fellow committer.

You should always consider compared to our huge user base we receive a very small amount of usable contributions.

Please go on, triage that ticket and merge the commit with the ticket id.

@jsoref thanks again!

**Comment by eolivelli** [comment]
Okay so I will continue with this ticket and eventually merge it to master.

**Comment by eolivelli** [comment]
Last run of CI, then merging
https://builds.apache.org/job/maven-box/job/maven-enforcer/job/MENFORCER-324/

**Comment by jira-importer** [comment]
Resolve #803

**Pull request closed without merging**
