### PR TITLE
[MENFORCER-142] documentation - add example for checking rules via cli

### PR DESCRIPTION
**Pull request by sparsick**
Introduce an example site with example "check specific rule via cli"

### CODE REVIEW

**Comment by khmarbaise** [comment]
Your PR has been merged. Thanks for your contribution. You can close your PR...

**Comment by aleguerrini** [comment]
Hi. When this feature could be release on public mvn repo ?

Thanks.

**Comment by robstoll** [comment]
I would have use for this as well, when is 3.0.0-M3 released?

**Comment by lvthillo** [comment]
Waiting for this too.

**Comment by lvthillo** [comment]
Waiting for this too.

**Comment by lvthillo** [comment]
Waiting for this too.

**Comment by lvthillo** [comment]
I'm waiting for this too.

**Comment by lvthillo** [comment]
Waiting for this too.

**Comment by j3ffrw** [comment]
this will be very useful in our pipelines, when can we have this released? My use case is like this

mvn enforcer:enforce -Drules=org.apache.maven.plugins.enforcer.RequireReleaseDeps
mvn versions:set -DnewVersion=$BUMP_VERSION

essentially my ci will not bump the project version if there are SNAPSHOT dependencies. but at the same time we would not like it to be in pom, binding enforcer to a non existing phase would not work, because not all my projects do have enforcer as plugin.

**Comment by Mazorius** [comment]
Hi @khmarbaise ,

did you know when the next release will be build?

I will currently try to use a snapshot but it would be nice if we got a official release version.

Thanks @sparsick for your fix! ;)

**Comment by destebanm** [comment]
HI!

I am using maven-enforcer-plugin:3.0.0-M2.

I have this in my pom.xml and it is working fine when `mvn verify`

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-banned-dependencies</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <bannedDependencies>
                                    <excludes>
                                        <exclude>x.y:logger:(,10.93)</exclude>
                                        <exclude>x.y:soap-utils:(,10.93)</exclude>
                                        <exclude>x.y:correlation-id:(,10.93)</exclude>
                                    </excludes>
                                </bannedDependencies>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
Is there any way to get rid of pom.xml setup and get the same behaviour with the CLI?

Thanks!

**Comment by Mazorius** [comment]
@destebanm until 3.0.0-M3 release no CLI is possible with rules.

In the master branch you can build the sources and use it till the release is done.

I do the same.

**Comment by destebanm** [comment]
Thanks @Mazorius!

Do you know when the release is expected?

**Comment by Mazorius** [comment]
> Do you know when the release is expected?

I know as much as you do. :-)

**Comment by destebanm** [comment]
Hi!

I have built the snapshot and the CLI is working but I don´t know how to use it.
I am able to run commands like that:
`mvn enforcer:enforce -Drules=alwaysFail`

but I would like to run this with the CLI

```
        <bannedDependencies>
           <excludes>
              <exclude>x.y:logger:(,10.93)</exclude>
              <exclude>x.y:soap-utils:(,10.93)</exclude>
              <exclude>x.y:correlation-id:(,10.93)</exclude>
           </excludes>
        </bannedDependencies>
```
Is there any kind of documentation about how to use the CLI??
Thanks!!

**Comment by rfscholte** [comment]
I had me doubts about this feature, but the commmunity was asking for it and it didn't really do any harm, but it is kind of un-Maven-ish. 
Being able to enforce rules from commandline means you cannot configure them. 
Maybe this feature should be pushed to a higher level (maven-core) to solve this for plugins in general.

**Comment by sparsick** [comment]
@destebanm yes, a documentation exists for this feature. But it also isn't release. But you can generate it by yourself with the following commands:

````
mvn clean verify site
```` 

Open in your browser the following file
````
<path to enforce project>/maven-enforcer-plugin/target/site/examples/check-specific-rule-via-cli.html
````

Your command looks well. No idea without debugging, why it is ignoring your setting.

**Comment by BenjenJones** [comment]
Any news on the M3?
This would be really helpful

**Comment by jira-importer** [comment]
Resolve #634

**Comment by jira-importer** [comment]
Resolve #634

**Pull request merged**
