### PR TITLE
[MENFORCER-288] Support new Java versioning schema for older versions.

### PR DESCRIPTION
**Pull request by bmhm**
Signed-off-by: Benjamin Marwell <bmarwell@gmail.com>

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MENFORCER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MENFORCER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MENFORCER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by bmhm** [comment]
While I still not like the forced else, I added it as requested in other PRs. Note that this will make the commit much bigger, because there is need to re-indent a lot of code. If granted, I will happily change it to:

```java
        if ( PATTERN_MAIN_OLD_JDK.matcher( theJdkVersion ).matches() )
        {
            return "1." + theJdkVersion;
        }
```

This would remove all those unnecessary changes:
https://github.com/apache/maven-enforcer/pull/58/files#diff-e944db4bfa78de9044a8e0b7ff8f51c5R81-R112

**Comment by rfscholte** [comment]
Consider using https://codehaus-plexus.github.io/plexus-languages/plexus-java/apidocs/org/codehaus/plexus/languages/java/version/JavaVersion.html whioch is already used by several other maven-plugins

**Comment by bmhm** [comment]
> Consider using https://codehaus-plexus.github.io/plexus-languages/plexus-java/apidocs/org/codehaus/plexus/languages/java/version/JavaVersion.html whioch is already used by several other maven-plugins

The contribution docs state that changes should be kept minimal. Please open an issue "migrate to `JavaVersion`", then I'll be happy to submit another PR.

**Comment by bmhm** [comment]
@rfscholte 
I just did take a look at `JavaVersion` from plexus-java you linked. That would not be much help, because even if you input "8" it cannot convert to `1.8`. I'd have to rewrite the whole logic. I'm not doing this without consent.

**Comment by bmhm** [comment]
Oh I think I missed the most important part:
```java
        enforceVersion( helper.getLog(), "JDK", getVersion(), detectedJdkVersion );
```
should become
```java
        enforceVersion( helper.getLog(), "JDK", normalizeJDKVersion( getVersion() ), detectedJdkVersion );
```

**Comment by rfscholte** [comment]
The rule `requireJavaVersion` is about comparing version, which is the main task of `JavaVersion`.
I'm pretty sure the `normalizeJDKVersion` can be replaced/removed. (and it would make comparison equal to other plugins)

**Comment by bmhm** [comment]
> I'm pretty sure the normalizeJDKVersion can be replaced/removed. (and it would make comparison equal to other plugins)

Yes, but now I'm building a method to parse `getVersion()` which could be anything like "[8,11]" or "(,1.7],[1.8,),6,7" or something. They need to get normalized first, don't they? That's a LOT of  probable impact. And a lot of tests cannot be used anymore. :(

**Comment by bmhm** [comment]
Actually, `enforceVersion` compares the systemProperty against a version range. The version range must be normalized or each put through JavaVersion.parse(). But this will not help, because if the range says (6 through 8), JavaVersion.compare will not accept with a VersionRange argument.

Example:
I use 
```java
<requireJavaVersion>
    <version>(,7),(7,)</version> <!-- not java 7 -->
</requireJavaVersion>
```

Then I get `JavaVersion("1.7")` from the system property. The `compareTo` method is useless, and the version range cannot be normalized. I do not thing `getVersion` should be parsed before handling over to the `enforceVersion` method. Should it?

**Comment by bmhm** [comment]
Thinking about what I just wrote:
Accepting a version range "6" but not "[6,7]" does not make sense. I'll remove this PR.

**Comment by jira-importer** [comment]
Resolve #772

**Pull request closed without merging**
