### PR TITLE
[MENFORCER-195] Fix to enforcer dependencyConvergence rule to support…

### PR DESCRIPTION
**Pull request by fbyrne**
Hi, 
Adding this pull request as a fix for [MENFORCER-195].  

Please disregard if the existing PR is sufficient.

Kind regards, 
Fergus

### CODE REVIEW

**Comment by fbyrne** [comment]
Duplicate of #20

**Comment by fbyrne** [comment]
Reopening as PR #20 is open since 2016 with no activity.

**Comment by rfscholte** [comment]
I worked together with Ray Tsang on this, after a lot of digging we discovered the real fix requires a change in Maven Core, see https://github.com/apache/maven/pull/269.
This PR doesn't have a test to confirm the fix, https://github.com/apache/maven-enforcer/pull/56 does.
So I'll close this one in favor of the other two PRs

**Comment by jira-importer** [comment]
Resolve #692

**Pull request closed without merging**
