### PR TITLE
[MENFORCER-314] - Warn if EnforcerRuleException has no message

### PR DESCRIPTION
**Pull request by famod**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MENFORCER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MENFORCER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MENFORCER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by famod** [comment]
I pushed an alternative approach because I couldn't really decide which one is better: #44

Please merge whichever PR you like best.

**Comment by eolivelli** [comment]
@famod I prefer this one.
Can you add a simple integration test ? This way in the future we would not add regressions.

I will be happy to merge as soon as we have the test.

cc @khmarbaise

**Comment by famod** [comment]
@eolivelli I had a quick look at the existing integration tests and I have to say that I have **no** clue how to test this very specific (and rare) case with capabilities of maven-invoker-plugin.
I mean, I would need to provoke a NPE or similar in a existing rule. How would one do that?

Extending `TestEnforceMojo` seems more doable, IMHO.

**Comment by famod** [comment]
I jumped ahead and extended `TestEnforceMojo`. IMHO this should be sufficient for such a small change.

Please note that I won't be able to put much more effort into this entire issue as I am busy elsewhere.

PS: Yes, I did see that there is a custom `MockEnforcerRule` but I saw no real sense in extending this with more logic as mockito is just way more flexible at such tasks (and you need to write less code).

**Comment by eolivelli** [comment]
@famod great work.

Will commit soon

**Comment by eolivelli** [comment]
waiting for CI
https://builds.apache.org/job/maven-box/job/maven-enforcer/job/MENFORCER-314/

**Comment by famod** [comment]
You are welcome and thank you, too!

**Comment by jira-importer** [comment]
Resolve #794

**Pull request closed without merging**
