### PR TITLE
[MENFORCER-272] Site fixes

### PR DESCRIPTION
**Pull request by jglick**
[MENFORCER-272](https://issues.apache.org/jira/browse/MENFORCER-272)

Some fixes I found desirable or necessary when testing site generation locally.

@reviewbybees for my colleagues

### CODE REVIEW

**Comment by jglick** [comment]
@reviewbybees done

**Comment by stephenc** [comment]
@jglick can you create a JIRA issue in MENFORCER project and I'll see about merging tomorrow

**Comment by stephenc** [comment]
@jglick you need to update the commit messages to contain `[MENFORCER-272]`

**Comment by jglick** [comment]
done

**Comment by stephenc** [comment]
@jglick merged in https://svn.apache.org/viewvc?view=revision&revision=1798818 , can you close this PR (the fun of GitHub PRs on SVN based project)

**Comment by jira-importer** [comment]
Resolve #755

**Comment by jira-importer** [comment]
Resolve #755

**Pull request closed without merging**
