### PR TITLE
Add Unit tests for RequireUpperBoundDeps

### PR DESCRIPTION
**Pull request by oleg-nenashev**
I decoupled the test improvements commit from #25. It just adds new tests for the existing functionality.

@reviewbybees @jglick @stephenc

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
@hboutemy @jglick Do you need any actions from me here?

**Comment by khmarbaise** [comment]
I've taken the PR#26 into MENFORCER-276 branch...lets see what our CI says...

**Comment by elharo** [comment]
Since this is several years old, I'm going to close it. Feel free to open a new PR that resolves the merge conflicts.

**Pull request closed without merging**
