### PR TITLE
[MENFORCER-319] Handle UTF-8 BOM when parsing pom.xml files

### PR DESCRIPTION
**Pull request by wilx**
Handle parsing of pom.xml in BanDuplicatePomDependencyVersions.java
similarly to how actual Maven model parser handles it to fix handling
of pom.xml files with UTF-8 BOM.

* * *

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MENFORCER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes. [MENFORCER-319](https://issues.apache.org/jira/browse/MENFORCER-319)
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MENFORCER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MENFORCER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by khmarbaise** [comment]
The patch looks good so far but unfortunately I don't see a test case for that..

**Comment by wilx** [comment]
[**@khmarbaise**](https://github.com/khmarbaise) commented on [14 Nov 2018, 00:59 CET](https://github.com/apache/maven-enforcer/pull/45#issuecomment-438485075 "2018-11-13T23:59:34Z - Replied by Github Reply Comments"):
> The patch looks good so far but unfortunately I don't see a test case for that..

I have updated pom.xml of integration test of banDuplicatePomDependencyVersions rule to be in UTF-8 BOM encoding.

**Comment by khmarbaise** [comment]
Please don't change existing tests...please add a new one!

**Comment by wilx** [comment]
[**@khmarbaise**](https://github.com/khmarbaise) commented on [Nov 14, 2018, 2:48 PM GMT+1](https://github.com/apache/maven-enforcer/pull/45#issuecomment-438667508 "2018-11-14T13:48:38Z - Replied by Github Reply Comments"):
> Please don't change existing tests...please add a new one!

I have reverted the previous modification and created a new test with UTF-8 BOM encoding.

**Comment by eolivelli** [comment]
CI is green.
As @khmarbaise already added comments I would like to have his opinion before committing.

thanks @wilx

**Comment by khmarbaise** [comment]
From my point of view looks fine now.

**Comment by eolivelli** [comment]
committed as c2f1ce236a6be3654c27aa27d1595f0aeb23fd9c

**Pull request closed without merging**
